### ISSUE TITLE
Changes are made only to the current configuration (tipically Debug)

### ISSUE THREAD

**Issue by bugnano** [akofman/cordova-plugin-add-swift-support#12]
I'm using this plugin in order to build a plugin I wrote ( https://bitbucket.org/bugnano/cordova-plugin-networking-multipeer ).

EMBEDDED_CONTENT_CONTAINS_SWIFT is set to YES and LD_RUNPATH_SEARCH_PATHS is set to "@executable_path/Frameworks" only for the Debug configuration.

The problem is that when trying to submit the app to the App Store, it has to be compiled in the Release configuration, and those 2 settings have to be changed manually, as this plugin does not set them correctly (otherwise the app will crash on startup).

I propose to change the settings in all the possible configurations, not just for the current one.

**Comment by akofman** [comment]
Hello,

I didn't have time to reproduce this issue but it seems to be related to this PR : https://github.com/akofman/cordova-plugin-add-swift-support/pull/11, could you check it and let me know if it's fine with this fixe ?
