### ISSUE TITLE
Set "Legacy Swift Language Version"

### ISSUE THREAD

**Issue by NiklasMerz** [akofman/cordova-plugin-add-swift-support#15]
Maybe I did something wrong, but I must set "Use Legacy Language Version" to Yes or No to successfully build my project. I use Xcode 8. An option simple to set this in my plugin would be nice.

**Comment by akofman** [comment]
If you are using a Swift 3 code base for your plugins the swift version is well configured. In case you now want to use a legacy code base you can configure this plugin with the following preference : `<preference name="UseLegacySwiftLanguageVersion" value="true" />`
