### ISSUE TITLE
Debug builds should be compiled without optimizations

### ISSUE THREAD

**Issue by kalliste** [akofman/cordova-plugin-add-swift-support#18]
Currently by default the Swift Compiler - Code Generation > Optimization Level setting is set to Fast for both Debug and Release. If you open the project in XCode to investigate a crash, debugging symbols are not available. It would be nice to have it set this to None for Debug builds.

**Comment by akofman** [comment]
Hmmm, in my case it is configured to None for Debug mode. Which version of XCode are you using ?

**Comment by kalliste** [comment]
I have XCode 7.3

**Comment by akofman** [comment]
Fixed in version 1.6.0 thanks to @viskin PR.
