### ISSUE TITLE
Error: undefined is not a function

### ISSUE THREAD

**Issue by metalaureate** [akofman/cordova-plugin-add-swift-support#22]
Encountered this error when trying to us https://github.com/terikon/cordova-plugin-photo-library/issues/4, and isolate it to this plugin.

The error prevents iOS or Android from building projects.

```
cordova plugin add cordova-plugin-add-swift-support --save
Fetching plugin "cordova-plugin-add-swift-support" via npm
Installing "cordova-plugin-add-swift-support" for android
Installing "cordova-plugin-add-swift-support" for ios
Saved plugin info for "cordova-plugin-add-swift-support" to config.xml
Error: undefined is not a function
```

Cordova CLI: 6.1.1
Gulp version: CLI version 3.9.1
Gulp local:
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v0.12.2
Xcode version: Xcode 8.0 Build version 8A218a

Appreciate any help... lost in dependency land here.

**Comment by akofman** [comment]
Hello,

I think you need to upgrade your node version. I will update the README to inform about the minimal version compatibility.

**Comment by metalaureate** [comment]
That fixed it thanks.

**Comment by DesarrolloES** [comment]
What is the minimal version compatibility for node?
