### ISSUE TITLE
swift3 required me to explicitly expose plugin method

### ISSUE THREAD

**Issue by mixersoft** [akofman/cordova-plugin-add-swift-support#23]
I'm not sure if this is fixed here or elsewhere, but it was a problem.

I followed the howto at this link: http://moduscreate.com/writing-a-cordova-plugin-in-swift-for-ios/

I got an error that said the plugin method was not found

Then I read the comments, and it solved my problem.

http://disq.us/p/1cc487t

```
@objc(echo:) func echo(command: CDVInvokedUrlCommand) {
...
}
```

**Comment by akofman** [comment]
Hmm, did you tried the last version of this plugin ? I think it should be solved.
