### ISSUE TITLE
Phonegap Build Support

### ISSUE THREAD

**Issue by mevinDhun** [akofman/cordova-plugin-add-swift-support#28]
Hi, 
Does this plugin work with phonegap build? I tried using your plugin as a dependency of my plugin and i uploaded to the build service but it fails with:
```
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```
Since PGB does not support hooks, i assume this plugin will not work?

**Comment by jcesarmobile** [comment]
No, as PGB doesn't support hooks this plugin won't work there
