### ISSUE TITLE
Wrong text merged in Briding-Header.h

### ISSUE THREAD

**Issue by IvoMoor** [akofman/cordova-plugin-add-swift-support#31]
Hi,

By using your cordova plugin, I was able to create my own plugin using Swift 3. The plugin I created requires the CommonCrypto framework which needs to be added to the Bridging-Header file.

In order to do so, in my plugin.xml file I added:
```xml
<header-file src="MyPlugin-Bridging-Header.h"/>
```

Pointing to a file containing:
```swift
#import <CommonCrypto/CommonCrypto.h>
```

As dependency in the plugin.xml file I added:
```xml
<dependency id="cordova-plugin-add-swift-support"/>
```

After adding my plugin to my project, the Bridging-Header.h file in "Other Resources" has been changed, but instead of the file contents (# import <CommonCrypto/CommonCrypto.h>), the name of the file is merged. So the contents of the Bridging-Heder.h file is:
```swift
#import <Cordova/CDV.h>
#import "MyPlugin-Bridging-Header.h"
```

Am I doing anything wrong? Or is this a bug?

**Comment by akofman** [comment]
Hello !

To me your `Bridging-Header.h` file looks good like that. Maybe you need to add `CommonCrypto/CommonCrypto.h` as an header file in your `plugin.xml` ?

What's your actual error ?

**Comment by IvoMoor** [comment]
Ah, now I see. Sorry, my mistake. I expected the Bridging-Header.h file to look like:

```objective-c
#import <Cordova/CDV.h>
#import CommonCrypto/CommonCrypto.h
```

But I understand now that the Bridging-Header.h file is importing my header file which on its own contains the CommonCrypto library. So it looks like:
```objective-c
#import <Cordova/CDV.h>
#import "MyPlugin-Bridging-Heder.h"
```

Clear. It is working correctly. I am able to build my application.

Thanks!

Ivo
