### ISSUE TITLE
Missing tag and changelog for 1.7.0

### ISSUE THREAD

**Issue by elsesiy** [akofman/cordova-plugin-add-swift-support#33]
I'd love to know what exactly changed throughout the versions and if there any breaking changes.

As of now, I have to diff between various commits to determine the changes which is really not necessary in times of repositories like [this](https://github.com/skywinder/github-changelog-generator). 

Can you please tag the latest release and add the missing changelog?

Thanks!

**Comment by akofman** [comment]
Hello @elsesiy,

Thanks for this excellent link ! It works like a charm.
