### ISSUE TITLE
*-Briding-Header.h not used

### ISSUE THREAD

**Issue by t-knapp** [akofman/cordova-plugin-add-swift-support#48]
Hello,

I created a Custom-Plugin with Swift that depend on the `#import <CommonCrypto/CommonCrypto.h>` statement.
I adjusted the config.xml of the Plugin to import the content of my "Activation-Briding-Header.h" into cordovas one.

plugin.xml

`platform name="ios">
config-file target="config.xml" parent="/*">
feature name="Activation">
param name="ios-package" value="Activation"/>
/feature>
/config-file>
header-file src="src/ios/Activation-Bridging-Header.h" />
source-file src="src/ios/Activation.swift" />
framework src="lib/HandyJSON.framework" custom="true"/>
dependency id="cordova-plugin-add-swift-support"/>
/platform>`

It seems, the hook is not fired when I `cordova plugins add` the Plugin.

What am I doing wrong?

Kind regards
Tobias

**Comment by akofman** [comment]
Hello !

Actually you don't have to adjust your config.xml, this plugin will automatically detect your bridging headers.
Please check you have well included your header and source files in your `plugin.xml` as it is done as an example in this plugin: https://github.com/akofman/cordova-plugin-permissionScope/blob/master/plugin.xml.

**Comment by NeoLSN** [comment]
I also met the same issue. The hook is not fired after `cordova plugins add` on `cordova-plugin-add-swift-support@1.7.1`.

**Comment by t-knapp** [comment]
@NeoLSN Thanks for that hint. Ich also use version 1.7.1.

**Comment by akofman** [comment]
I close this issue because I think this is the same issue resolved in PR #52
