### ISSUE TITLE
Implement catching promise rejections

### ISSUE THREAD

**Issue by benjamin-bueckendorf** [akofman/cordova-plugin-add-swift-support#51]
Hi,

promise rejections of functions like `getPlatformVersionsFromFileSystem` are not caught, thus if something fails other cordova plugins are not added to the Bridging-Header.h and builds may fail.

`getPlatformVersionsFromFileSystem` failed for me due to a folder in the projectRoot containing a special character, but since the rejection was not caught this was very difficult to figure out.

Otherwise great plugin!

Regards

**Comment by TheLiquidSky** [comment]
This is relevant to my PR #52.

**Comment by akofman** [comment]
Fixed in PR #52
