### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by l3ender** [akofman/cordova-plugin-add-swift-support#55]
Is there plans for support for Swift 4? Are you open to PRs, and if so, could an overview of what needs to be done for support?

Thanks!

**Comment by RobbertWolfs** [comment]
swift 5 since yesterday 🤦‍♂️

**Comment by timbru31** [comment]
Setting `<preference name="UseSwiftLanguageVersion" value="5" />` works fine for me and Xcode sets the correct compiler level:

![image](https://user-images.githubusercontent.com/838003/55104690-2cb2a880-50cb-11e9-934d-964c7041c561.png)

**Comment by cleversolutions** [comment]
As documented in the README try adding this to your plugin.xml
<preference name="UseSwiftLanguageVersion" value="5" />

**Comment by timbru31** [comment]
Sidenote: my PR #57 makes Swift 4 the new default. :)
