### ISSUE TITLE
How to use this project?

### ISSUE THREAD

**Issue by Jessting** [akofman/cordova-plugin-add-swift-support#60]

**Comment by Jessting** [comment]
Is there a detailed description of this project?

**Comment by byronaltice** [comment]
Check the README.md https://github.com/akofman/cordova-plugin-add-swift-support

**Comment by Jessting** [comment]
I've read it, but I still don't understand. So is there a more detailed explanation？I have an app for iOS that has already been written. So make it into a plug-in, and then use your plugin? Or do you use this project directly?

**Comment by akofman** [comment]
Hello @Jessting, you won't find anything more than the README as a documentation but, it's been enough until then :) To clarify, this plugin will permit you to write the iOS part of your Cordova plugin using the Swift language. An article has been written about how to use it, maybe it will be clearer for you : https://moduscreate.com/blog/writing-a-cordova-plugin-in-swift-for-ios/. 

Also in your last comment you're talking about an app, what is exactly your need ?

**Comment by Jessting** [comment]
First of all, @akofman, thank you for your answer. Then I've written an iOS application project that I want to integrate into Cordova's new project. That's my goal.

**Comment by akofman** [comment]
Hmmm ok, and if you already have an app, why would you want to convert it into a Cordova project ? The main goal of Cordova is to write an app from web technologies, in your case, if I got it well, you already have an iOS app written in Swift ?

**Comment by Jessting** [comment]
Yes, I've written an iOS native project with swift, but I want to use this project as another sub-module of the project created with Cordova. I'm sorry I don't know how to operate it.

**Comment by akofman** [comment]
Maybe writing your own plugin embedding your app and presenting it from a modal (else I think you will have navigation issues between your views and the Cordova Webview) is a solution. You should talk with the Cordova Slack community (http://slack.cordova.io/), I'm sure they will definitely help you. Sorry if I can't help you more here but what you're trying to do is more than something related to this plugin in particular actually.

**Comment by Jessting** [comment]
Thank you very much for your answer, @akofman .I find it really difficult to implement my idea. Now I am inquiring about the information for my project. Last but not least， thank you for your ideas.
